version: "1"
projects:
- name: server status
  environments:
  - name: Production
    services:
    - type: web
      name: server-status
      runtime: node
      repo: https://github.com/serverstatus-control/siteprova
      plan: free
      envVars:
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      - key: DATABASE_URL
        sync: false
      region: oregon
      buildCommand: npm install && npm run build
      startCommand: npm start
      autoDeployTrigger: commit
